#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_SK_Slug

#include "Basic.hpp"

#include "AnimBP_SK_Slug_classes.hpp"
#include "AnimBP_SK_Slug_parameters.hpp"


namespace SDK
{

// Function AnimBP_SK_Slug.AnimBP_SK_Slug_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UAnimBP_SK_Slug_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_SK_Slug_C", "AnimGraph");

	Params::AnimBP_SK_Slug_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function AnimBP_SK_Slug.AnimBP_SK_Slug_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_SK_Slug_AnimGraphNode_SequencePlayer_63435F634EF556FA04B0199D01672758
// (BlueprintEvent)

void UAnimBP_SK_Slug_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_SK_Slug_AnimGraphNode_SequencePlayer_63435F634EF556FA04B0199D01672758()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_SK_Slug_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_SK_Slug_AnimGraphNode_SequencePlayer_63435F634EF556FA04B0199D01672758");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_SK_Slug.AnimBP_SK_Slug_C.ExecuteUbergraph_AnimBP_SK_Slug
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_SK_Slug_C::ExecuteUbergraph_AnimBP_SK_Slug(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_SK_Slug_C", "ExecuteUbergraph_AnimBP_SK_Slug");

	Params::AnimBP_SK_Slug_C_ExecuteUbergraph_AnimBP_SK_Slug Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

