#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_SK_Ant

#include "Basic.hpp"

#include "AnimBP_SK_Ant_classes.hpp"
#include "AnimBP_SK_Ant_parameters.hpp"


namespace SDK
{

// Function AnimBP_SK_Ant.AnimBP_SK_Ant_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void UAnimBP_SK_Ant_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_SK_Ant_C", "AnimGraph");

	Params::AnimBP_SK_Ant_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function AnimBP_SK_Ant.AnimBP_SK_Ant_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_SK_Ant_AnimGraphNode_SequencePlayer_D2AABB1245CF5D4315EE3682432C4FC1
// (BlueprintEvent)

void UAnimBP_SK_Ant_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_SK_Ant_AnimGraphNode_SequencePlayer_D2AABB1245CF5D4315EE3682432C4FC1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_SK_Ant_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_SK_Ant_AnimGraphNode_SequencePlayer_D2AABB1245CF5D4315EE3682432C4FC1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_SK_Ant.AnimBP_SK_Ant_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_SK_Ant_AnimGraphNode_TransitionResult_EFD531AF4CCCF35426237183F9A8C589
// (BlueprintEvent)

void UAnimBP_SK_Ant_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_SK_Ant_AnimGraphNode_TransitionResult_EFD531AF4CCCF35426237183F9A8C589()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_SK_Ant_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_SK_Ant_AnimGraphNode_TransitionResult_EFD531AF4CCCF35426237183F9A8C589");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_SK_Ant.AnimBP_SK_Ant_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_SK_Ant_AnimGraphNode_TransitionResult_7D0F405F45D240C59EC504B10106FE14
// (BlueprintEvent)

void UAnimBP_SK_Ant_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_SK_Ant_AnimGraphNode_TransitionResult_7D0F405F45D240C59EC504B10106FE14()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_SK_Ant_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_SK_Ant_AnimGraphNode_TransitionResult_7D0F405F45D240C59EC504B10106FE14");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_SK_Ant.AnimBP_SK_Ant_C.ExecuteUbergraph_AnimBP_SK_Ant
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_SK_Ant_C::ExecuteUbergraph_AnimBP_SK_Ant(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_SK_Ant_C", "ExecuteUbergraph_AnimBP_SK_Ant");

	Params::AnimBP_SK_Ant_C_ExecuteUbergraph_AnimBP_SK_Ant Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

