#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_SK_Pufferfish

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CrabChampions_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AnimBP_SK_Pufferfish.AnimBP_SK_Pufferfish_C
// 0x00C0 (0x03A0 - 0x02E0)
class UAnimBP_SK_Pufferfish_C final : public UCrabEnemyAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02E8(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0318(0x0080)()

public:
	void AnimGraph(struct FPoseLink* Param_AnimGraph);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_SK_Pufferfish_AnimGraphNode_SequencePlayer_869AA08746C9DE95EEAE2895CB29DEC6();
	void ExecuteUbergraph_AnimBP_SK_Pufferfish(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AnimBP_SK_Pufferfish_C">();
	}
	static class UAnimBP_SK_Pufferfish_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimBP_SK_Pufferfish_C>();
	}
};
static_assert(alignof(UAnimBP_SK_Pufferfish_C) == 0x000010, "Wrong alignment on UAnimBP_SK_Pufferfish_C");
static_assert(sizeof(UAnimBP_SK_Pufferfish_C) == 0x0003A0, "Wrong size on UAnimBP_SK_Pufferfish_C");
static_assert(offsetof(UAnimBP_SK_Pufferfish_C, UberGraphFrame) == 0x0002E0, "Member 'UAnimBP_SK_Pufferfish_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAnimBP_SK_Pufferfish_C, AnimGraphNode_Root) == 0x0002E8, "Member 'UAnimBP_SK_Pufferfish_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UAnimBP_SK_Pufferfish_C, AnimGraphNode_SequencePlayer) == 0x000318, "Member 'UAnimBP_SK_Pufferfish_C::AnimGraphNode_SequencePlayer' has a wrong offset!");

}

