#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_SK_Pumpkin

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function AnimBP_SK_Pumpkin.AnimBP_SK_Pumpkin_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct AnimBP_SK_Pumpkin_C_AnimGraph final
{
public:
	struct FPoseLink                              Param_AnimGraph;                                   // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(AnimBP_SK_Pumpkin_C_AnimGraph) == 0x000008, "Wrong alignment on AnimBP_SK_Pumpkin_C_AnimGraph");
static_assert(sizeof(AnimBP_SK_Pumpkin_C_AnimGraph) == 0x000010, "Wrong size on AnimBP_SK_Pumpkin_C_AnimGraph");
static_assert(offsetof(AnimBP_SK_Pumpkin_C_AnimGraph, Param_AnimGraph) == 0x000000, "Member 'AnimBP_SK_Pumpkin_C_AnimGraph::Param_AnimGraph' has a wrong offset!");

// Function AnimBP_SK_Pumpkin.AnimBP_SK_Pumpkin_C.ExecuteUbergraph_AnimBP_SK_Pumpkin
// 0x0004 (0x0004 - 0x0000)
struct AnimBP_SK_Pumpkin_C_ExecuteUbergraph_AnimBP_SK_Pumpkin final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AnimBP_SK_Pumpkin_C_ExecuteUbergraph_AnimBP_SK_Pumpkin) == 0x000004, "Wrong alignment on AnimBP_SK_Pumpkin_C_ExecuteUbergraph_AnimBP_SK_Pumpkin");
static_assert(sizeof(AnimBP_SK_Pumpkin_C_ExecuteUbergraph_AnimBP_SK_Pumpkin) == 0x000004, "Wrong size on AnimBP_SK_Pumpkin_C_ExecuteUbergraph_AnimBP_SK_Pumpkin");
static_assert(offsetof(AnimBP_SK_Pumpkin_C_ExecuteUbergraph_AnimBP_SK_Pumpkin, EntryPoint) == 0x000000, "Member 'AnimBP_SK_Pumpkin_C_ExecuteUbergraph_AnimBP_SK_Pumpkin::EntryPoint' has a wrong offset!");

}

