#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_SK_Slug

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function AnimBP_SK_Slug.AnimBP_SK_Slug_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct AnimBP_SK_Slug_C_AnimGraph final
{
public:
	struct FPoseLink                              Param_AnimGraph;                                   // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(AnimBP_SK_Slug_C_AnimGraph) == 0x000008, "Wrong alignment on AnimBP_SK_Slug_C_AnimGraph");
static_assert(sizeof(AnimBP_SK_Slug_C_AnimGraph) == 0x000010, "Wrong size on AnimBP_SK_Slug_C_AnimGraph");
static_assert(offsetof(AnimBP_SK_Slug_C_AnimGraph, Param_AnimGraph) == 0x000000, "Member 'AnimBP_SK_Slug_C_AnimGraph::Param_AnimGraph' has a wrong offset!");

// Function AnimBP_SK_Slug.AnimBP_SK_Slug_C.ExecuteUbergraph_AnimBP_SK_Slug
// 0x0008 (0x0008 - 0x0000)
struct AnimBP_SK_Slug_C_ExecuteUbergraph_AnimBP_SK_Slug final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AnimBP_SK_Slug_C_ExecuteUbergraph_AnimBP_SK_Slug) == 0x000004, "Wrong alignment on AnimBP_SK_Slug_C_ExecuteUbergraph_AnimBP_SK_Slug");
static_assert(sizeof(AnimBP_SK_Slug_C_ExecuteUbergraph_AnimBP_SK_Slug) == 0x000008, "Wrong size on AnimBP_SK_Slug_C_ExecuteUbergraph_AnimBP_SK_Slug");
static_assert(offsetof(AnimBP_SK_Slug_C_ExecuteUbergraph_AnimBP_SK_Slug, EntryPoint) == 0x000000, "Member 'AnimBP_SK_Slug_C_ExecuteUbergraph_AnimBP_SK_Slug::EntryPoint' has a wrong offset!");
static_assert(offsetof(AnimBP_SK_Slug_C_ExecuteUbergraph_AnimBP_SK_Slug, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x000004, "Member 'AnimBP_SK_Slug_C_ExecuteUbergraph_AnimBP_SK_Slug::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");

}

