#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_C

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_C.BP_C_C
// 0x0000 (0x0AC0 - 0x0AC0)
class ABP_C_C final : public ACrabPlayerC
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_C_C">();
	}
	static class ABP_C_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_C_C>();
	}
};
static_assert(alignof(ABP_C_C) == 0x000010, "Wrong alignment on ABP_C_C");
static_assert(sizeof(ABP_C_C) == 0x000AC0, "Wrong size on ABP_C_C");

}

