#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Cosmetic_C

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Cosmetic_C.BP_Cosmetic_C_C
// 0x0000 (0x0268 - 0x0268)
class ABP_Cosmetic_C_C final : public ACrabCosmeticC
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Cosmetic_C_C">();
	}
	static class ABP_Cosmetic_C_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Cosmetic_C_C>();
	}
};
static_assert(alignof(ABP_Cosmetic_C_C) == 0x000008, "Wrong alignment on ABP_Cosmetic_C_C");
static_assert(sizeof(ABP_Cosmetic_C_C) == 0x000268, "Wrong size on ABP_Cosmetic_C_C");

}

