#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CameraShake_Explosion

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CameraShake_Explosion.BP_CameraShake_Explosion_C
// 0x0000 (0x00B0 - 0x00B0)
class UBP_CameraShake_Explosion_C final : public UCameraShakeBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CameraShake_Explosion_C">();
	}
	static class UBP_CameraShake_Explosion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CameraShake_Explosion_C>();
	}
};
static_assert(alignof(UBP_CameraShake_Explosion_C) == 0x000010, "Wrong alignment on UBP_CameraShake_Explosion_C");
static_assert(sizeof(UBP_CameraShake_Explosion_C) == 0x0000B0, "Wrong size on UBP_CameraShake_Explosion_C");

}

