#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EQC_BestEnemyCoreLoc

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_EQC_BestEnemyCoreLoc.BP_EQC_BestEnemyCoreLoc_C
// 0x0000 (0x0030 - 0x0030)
class UBP_EQC_BestEnemyCoreLoc_C final : public UCrabEnemyEQC
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_EQC_BestEnemyCoreLoc_C">();
	}
	static class UBP_EQC_BestEnemyCoreLoc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_EQC_BestEnemyCoreLoc_C>();
	}
};
static_assert(alignof(UBP_EQC_BestEnemyCoreLoc_C) == 0x000008, "Wrong alignment on UBP_EQC_BestEnemyCoreLoc_C");
static_assert(sizeof(UBP_EQC_BestEnemyCoreLoc_C) == 0x000030, "Wrong size on UBP_EQC_BestEnemyCoreLoc_C");

}

