#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EliteBarrelSkull_Barrel

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_EliteBarrelSkull_Barrel.BP_EliteBarrelSkull_Barrel_C
// 0x0000 (0x03E0 - 0x03E0)
class ABP_EliteBarrelSkull_Barrel_C final : public ACrabDestructible
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_EliteBarrelSkull_Barrel_C">();
	}
	static class ABP_EliteBarrelSkull_Barrel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EliteBarrelSkull_Barrel_C>();
	}
};
static_assert(alignof(ABP_EliteBarrelSkull_Barrel_C) == 0x000008, "Wrong alignment on ABP_EliteBarrelSkull_Barrel_C");
static_assert(sizeof(ABP_EliteBarrelSkull_Barrel_C) == 0x0003E0, "Wrong size on ABP_EliteBarrelSkull_Barrel_C");

}

