#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FireTurret

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FireTurret.BP_FireTurret_C
// 0x0000 (0x0338 - 0x0338)
class ABP_FireTurret_C final : public ACrabTurret
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FireTurret_C">();
	}
	static class ABP_FireTurret_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FireTurret_C>();
	}
};
static_assert(alignof(ABP_FireTurret_C) == 0x000008, "Wrong alignment on ABP_FireTurret_C");
static_assert(sizeof(ABP_FireTurret_C) == 0x000338, "Wrong size on ABP_FireTurret_C");

}

