#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LaunchPad

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LaunchPad.BP_LaunchPad_C
// 0x0000 (0x0268 - 0x0268)
class ABP_LaunchPad_C final : public ACrabLaunchPad
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LaunchPad_C">();
	}
	static class ABP_LaunchPad_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LaunchPad_C>();
	}
};
static_assert(alignof(ABP_LaunchPad_C) == 0x000008, "Wrong alignment on ABP_LaunchPad_C");
static_assert(sizeof(ABP_LaunchPad_C) == 0x000268, "Wrong size on ABP_LaunchPad_C");

}

