#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LM

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LM.BP_LM_C
// 0x0000 (0x0548 - 0x0548)
class ABP_LM_C final : public ACrabLM
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LM_C">();
	}
	static class ABP_LM_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_LM_C>();
	}
};
static_assert(alignof(ABP_LM_C) == 0x000008, "Wrong alignment on ABP_LM_C");
static_assert(sizeof(ABP_LM_C) == 0x000548, "Wrong size on ABP_LM_C");

}

