#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MortarTurret

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MortarTurret.BP_MortarTurret_C
// 0x0000 (0x0338 - 0x0338)
class ABP_MortarTurret_C final : public ACrabTurret
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MortarTurret_C">();
	}
	static class ABP_MortarTurret_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MortarTurret_C>();
	}
};
static_assert(alignof(ABP_MortarTurret_C) == 0x000008, "Wrong alignment on ABP_MortarTurret_C");
static_assert(sizeof(ABP_MortarTurret_C) == 0x000338, "Wrong size on ABP_MortarTurret_C");

}

