#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PhysicsActor_Crown

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PhysicsActor_Crown.BP_PhysicsActor_Crown_C
// 0x0000 (0x0268 - 0x0268)
class ABP_PhysicsActor_Crown_C final : public ACrabPhysicsActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PhysicsActor_Crown_C">();
	}
	static class ABP_PhysicsActor_Crown_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PhysicsActor_Crown_C>();
	}
};
static_assert(alignof(ABP_PhysicsActor_Crown_C) == 0x000008, "Wrong alignment on ABP_PhysicsActor_Crown_C");
static_assert(sizeof(ABP_PhysicsActor_Crown_C) == 0x000268, "Wrong size on ABP_PhysicsActor_Crown_C");

}

