#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PC

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PC.BP_PC_C
// 0x0000 (0x08C0 - 0x08C0)
class ABP_PC_C final : public ACrabPC
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PC_C">();
	}
	static class ABP_PC_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PC_C>();
	}
};
static_assert(alignof(ABP_PC_C) == 0x000008, "Wrong alignment on ABP_PC_C");
static_assert(sizeof(ABP_PC_C) == 0x0008C0, "Wrong size on ABP_PC_C");

}

