#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Pickup_Crystal

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Pickup_Crystal.BP_Pickup_Crystal_C
// 0x0000 (0x0270 - 0x0270)
class ABP_Pickup_Crystal_C final : public ACrabCrystalPickup
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Pickup_Crystal_C">();
	}
	static class ABP_Pickup_Crystal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Pickup_Crystal_C>();
	}
};
static_assert(alignof(ABP_Pickup_Crystal_C) == 0x000008, "Wrong alignment on ABP_Pickup_Crystal_C");
static_assert(sizeof(ABP_Pickup_Crystal_C) == 0x000270, "Wrong size on ABP_Pickup_Crystal_C");

}

