#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PoisonTurret

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PoisonTurret.BP_PoisonTurret_C
// 0x0000 (0x0338 - 0x0338)
class ABP_PoisonTurret_C final : public ACrabTurret
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PoisonTurret_C">();
	}
	static class ABP_PoisonTurret_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PoisonTurret_C>();
	}
};
static_assert(alignof(ABP_PoisonTurret_C) == 0x000008, "Wrong alignment on ABP_PoisonTurret_C");
static_assert(sizeof(ABP_PoisonTurret_C) == 0x000338, "Wrong size on ABP_PoisonTurret_C");

}

