#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SignUI

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SignUI.BP_SignUI_C
// 0x0028 (0x0248 - 0x0220)
class ABP_SignUI_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetComponent*                       Widget;                                            // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class FString                                 SignText;                                          // 0x0238(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_SignUI(int32 EntryPoint);
	void ReceiveBeginPlay();
	void UserConstructionScript();
	void RefreshSignUI();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SignUI_C">();
	}
	static class ABP_SignUI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SignUI_C>();
	}
};
static_assert(alignof(ABP_SignUI_C) == 0x000008, "Wrong alignment on ABP_SignUI_C");
static_assert(sizeof(ABP_SignUI_C) == 0x000248, "Wrong size on ABP_SignUI_C");
static_assert(offsetof(ABP_SignUI_C, UberGraphFrame) == 0x000220, "Member 'ABP_SignUI_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_SignUI_C, Widget) == 0x000228, "Member 'ABP_SignUI_C::Widget' has a wrong offset!");
static_assert(offsetof(ABP_SignUI_C, DefaultSceneRoot) == 0x000230, "Member 'ABP_SignUI_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(ABP_SignUI_C, SignText) == 0x000238, "Member 'ABP_SignUI_C::SignText' has a wrong offset!");

}

