#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StatsPedestal

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_StatsPedestal.BP_StatsPedestal_C
// 0x0000 (0x02A0 - 0x02A0)
class ABP_StatsPedestal_C final : public ACrabStatsPedestal
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_StatsPedestal_C">();
	}
	static class ABP_StatsPedestal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_StatsPedestal_C>();
	}
};
static_assert(alignof(ABP_StatsPedestal_C) == 0x000008, "Wrong alignment on ABP_StatsPedestal_C");
static_assert(sizeof(ABP_StatsPedestal_C) == 0x0002A0, "Wrong size on ABP_StatsPedestal_C");

}

