#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SignUI

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_SignUI.BP_SignUI_C.ExecuteUbergraph_BP_SignUI
// 0x0004 (0x0004 - 0x0000)
struct BP_SignUI_C_ExecuteUbergraph_BP_SignUI final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SignUI_C_ExecuteUbergraph_BP_SignUI) == 0x000004, "Wrong alignment on BP_SignUI_C_ExecuteUbergraph_BP_SignUI");
static_assert(sizeof(BP_SignUI_C_ExecuteUbergraph_BP_SignUI) == 0x000004, "Wrong size on BP_SignUI_C_ExecuteUbergraph_BP_SignUI");
static_assert(offsetof(BP_SignUI_C_ExecuteUbergraph_BP_SignUI, EntryPoint) == 0x000000, "Member 'BP_SignUI_C_ExecuteUbergraph_BP_SignUI::EntryPoint' has a wrong offset!");

// Function BP_SignUI.BP_SignUI_C.RefreshSignUI
// 0x0030 (0x0030 - 0x0000)
struct BP_SignUI_C_RefreshSignUI final
{
public:
	class UUserWidget*                            CallFunc_GetWidget_ReturnValue;                    // 0x0000(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0008(0x0018)()
	class UUI_Sign_C*                             K2Node_DynamicCast_AsUI_Sign;                      // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_SignUI_C_RefreshSignUI) == 0x000008, "Wrong alignment on BP_SignUI_C_RefreshSignUI");
static_assert(sizeof(BP_SignUI_C_RefreshSignUI) == 0x000030, "Wrong size on BP_SignUI_C_RefreshSignUI");
static_assert(offsetof(BP_SignUI_C_RefreshSignUI, CallFunc_GetWidget_ReturnValue) == 0x000000, "Member 'BP_SignUI_C_RefreshSignUI::CallFunc_GetWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SignUI_C_RefreshSignUI, CallFunc_Conv_StringToText_ReturnValue) == 0x000008, "Member 'BP_SignUI_C_RefreshSignUI::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SignUI_C_RefreshSignUI, K2Node_DynamicCast_AsUI_Sign) == 0x000020, "Member 'BP_SignUI_C_RefreshSignUI::K2Node_DynamicCast_AsUI_Sign' has a wrong offset!");
static_assert(offsetof(BP_SignUI_C_RefreshSignUI, K2Node_DynamicCast_bSuccess) == 0x000028, "Member 'BP_SignUI_C_RefreshSignUI::K2Node_DynamicCast_bSuccess' has a wrong offset!");

}

