#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SentryTurret

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SentryTurret.BP_SentryTurret_C
// 0x0000 (0x0338 - 0x0338)
class ABP_SentryTurret_C final : public ACrabTurret
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SentryTurret_C">();
	}
	static class ABP_SentryTurret_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SentryTurret_C>();
	}
};
static_assert(alignof(ABP_SentryTurret_C) == 0x000008, "Wrong alignment on ABP_SentryTurret_C");
static_assert(sizeof(ABP_SentryTurret_C) == 0x000338, "Wrong size on ABP_SentryTurret_C");

}

