#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SignUI

#include "Basic.hpp"

#include "BP_SignUI_classes.hpp"
#include "BP_SignUI_parameters.hpp"


namespace SDK
{

// Function BP_SignUI.BP_SignUI_C.ExecuteUbergraph_BP_SignUI
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_SignUI_C::ExecuteUbergraph_BP_SignUI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SignUI_C", "ExecuteUbergraph_BP_SignUI");

	Params::BP_SignUI_C_ExecuteUbergraph_BP_SignUI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_SignUI.BP_SignUI_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_SignUI_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SignUI_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SignUI.BP_SignUI_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_SignUI_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SignUI_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_SignUI.BP_SignUI_C.RefreshSignUI
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_SignUI_C::RefreshSignUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_SignUI_C", "RefreshSignUI");

	UObject::ProcessEvent(Func, nullptr);
}

}

