#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ShopPedestal

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ShopPedestal.BP_ShopPedestal_C
// 0x0000 (0x0260 - 0x0260)
class ABP_ShopPedestal_C final : public ACrabShopPedestal
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ShopPedestal_C">();
	}
	static class ABP_ShopPedestal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ShopPedestal_C>();
	}
};
static_assert(alignof(ABP_ShopPedestal_C) == 0x000008, "Wrong alignment on ABP_ShopPedestal_C");
static_assert(sizeof(ABP_ShopPedestal_C) == 0x000260, "Wrong size on ABP_ShopPedestal_C");

}

