#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GunInfoPanel

#include "Basic.hpp"

#include "GunInfoPanel_classes.hpp"
#include "GunInfoPanel_parameters.hpp"


namespace SDK
{

// Function GunInfoPanel.GunInfoPanel_C.ExecuteUbergraph_GunInfoPanel
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGunInfoPanel_C::ExecuteUbergraph_GunInfoPanel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GunInfoPanel_C", "ExecuteUbergraph_GunInfoPanel");

	Params::GunInfoPanel_C_ExecuteUbergraph_GunInfoPanel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GunInfoPanel.GunInfoPanel_C.StopCompareStats
// (Public, BlueprintCallable, BlueprintEvent)

void UGunInfoPanel_C::StopCompareStats()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GunInfoPanel_C", "StopCompareStats");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GunInfoPanel.GunInfoPanel_C.CompareStats
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Param_Accuracy                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_Capacity                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_Damage                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_Firerate                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_Recoil                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_ReloadTime                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGunInfoPanel_C::CompareStats(float Param_Accuracy, float Param_Capacity, float Param_Damage, float Param_Firerate, float Param_Recoil, float Param_ReloadTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GunInfoPanel_C", "CompareStats");

	Params::GunInfoPanel_C_CompareStats Parms{};

	Parms.Param_Accuracy = Param_Accuracy;
	Parms.Param_Capacity = Param_Capacity;
	Parms.Param_Damage = Param_Damage;
	Parms.Param_Firerate = Param_Firerate;
	Parms.Param_Recoil = Param_Recoil;
	Parms.Param_ReloadTime = Param_ReloadTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GunInfoPanel.GunInfoPanel_C.UpdateStats
// (BlueprintCallable, BlueprintEvent)

void UGunInfoPanel_C::UpdateStats()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GunInfoPanel_C", "UpdateStats");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GunInfoPanel.GunInfoPanel_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UGunInfoPanel_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GunInfoPanel_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

