#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RobberGameState

#include "Basic.hpp"

#include "RobberGameState_classes.hpp"
#include "RobberGameState_parameters.hpp"


namespace SDK
{

// Function RobberGameState.RobberGameState_C.PowerSet__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Total                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Minimum                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_PowerMultiplier                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ARobberGameState_C::PowerSet__DelegateSignature(int32 Total, int32 Minimum, float Param_PowerMultiplier)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RobberGameState_C", "PowerSet__DelegateSignature");

	Params::RobberGameState_C_PowerSet__DelegateSignature Parms{};

	Parms.Total = Total;
	Parms.Minimum = Minimum;
	Parms.Param_PowerMultiplier = Param_PowerMultiplier;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RobberGameState.RobberGameState_C.ExecuteUbergraph_RobberGameState
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ARobberGameState_C::ExecuteUbergraph_RobberGameState(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RobberGameState_C", "ExecuteUbergraph_RobberGameState");

	Params::RobberGameState_C_ExecuteUbergraph_RobberGameState Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RobberGameState.RobberGameState_C.SetFirepower
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ARobberGameState_C::SetFirepower()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RobberGameState_C", "SetFirepower");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RobberGameState.RobberGameState_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ARobberGameState_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RobberGameState_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RobberGameState.RobberGameState_C.SpawnToolsWhenConnected
// (BlueprintCallable, BlueprintEvent)

void ARobberGameState_C::SpawnToolsWhenConnected()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RobberGameState_C", "SpawnToolsWhenConnected");

	UObject::ProcessEvent(Func, nullptr);
}


// Function RobberGameState.RobberGameState_C.GetTotalPlayerPower
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_Total_power                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_MinimumPower                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ARobberGameState_C::GetTotalPlayerPower(int32* Param_Total_power, int32* Param_MinimumPower)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RobberGameState_C", "GetTotalPlayerPower");

	Params::RobberGameState_C_GetTotalPlayerPower Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_Total_power != nullptr)
		*Param_Total_power = Parms.Param_Total_power;

	if (Param_MinimumPower != nullptr)
		*Param_MinimumPower = Parms.Param_MinimumPower;
}


// Function RobberGameState.RobberGameState_C.CheckPlayersLoaded
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Loaded_                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ARobberGameState_C::CheckPlayersLoaded(bool* Loaded_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RobberGameState_C", "CheckPlayersLoaded");

	Params::RobberGameState_C_CheckPlayersLoaded Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Loaded_ != nullptr)
		*Loaded_ = Parms.Loaded_;
}

}

