#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SK_Crab_AnimBP_Enemy

#include "Basic.hpp"

#include "SK_Crab_AnimBP_Enemy_classes.hpp"
#include "SK_Crab_AnimBP_Enemy_parameters.hpp"


namespace SDK
{

// Function SK_Crab_AnimBP_Enemy.SK_Crab_AnimBP_Enemy_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void USK_Crab_AnimBP_Enemy_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_Enemy_C", "AnimGraph");

	Params::SK_Crab_AnimBP_Enemy_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function SK_Crab_AnimBP_Enemy.SK_Crab_AnimBP_Enemy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_BlendSpacePlayer_F3EF04094EB895D6B20F42A20A3AE705
// (BlueprintEvent)

void USK_Crab_AnimBP_Enemy_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_BlendSpacePlayer_F3EF04094EB895D6B20F42A20A3AE705()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_Enemy_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_BlendSpacePlayer_F3EF04094EB895D6B20F42A20A3AE705");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Crab_AnimBP_Enemy.SK_Crab_AnimBP_Enemy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_DD6C5B45424C4923F0B97B97F2DC0A48
// (BlueprintEvent)

void USK_Crab_AnimBP_Enemy_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_DD6C5B45424C4923F0B97B97F2DC0A48()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_Enemy_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_DD6C5B45424C4923F0B97B97F2DC0A48");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Crab_AnimBP_Enemy.SK_Crab_AnimBP_Enemy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_1F263FEE4CD1ACA6F8D1929A772145F9
// (BlueprintEvent)

void USK_Crab_AnimBP_Enemy_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_1F263FEE4CD1ACA6F8D1929A772145F9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_Enemy_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_1F263FEE4CD1ACA6F8D1929A772145F9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Crab_AnimBP_Enemy.SK_Crab_AnimBP_Enemy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_6384B838415B210E76C0E29D0CDA5515
// (BlueprintEvent)

void USK_Crab_AnimBP_Enemy_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_6384B838415B210E76C0E29D0CDA5515()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_Enemy_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_6384B838415B210E76C0E29D0CDA5515");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Crab_AnimBP_Enemy.SK_Crab_AnimBP_Enemy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_6738C0EE4CEC17D99C5117869B7001BE
// (BlueprintEvent)

void USK_Crab_AnimBP_Enemy_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_6738C0EE4CEC17D99C5117869B7001BE()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_Enemy_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_6738C0EE4CEC17D99C5117869B7001BE");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Crab_AnimBP_Enemy.SK_Crab_AnimBP_Enemy_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_DD8F65FF423482C538A43999A4629F14
// (BlueprintEvent)

void USK_Crab_AnimBP_Enemy_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_DD8F65FF423482C538A43999A4629F14()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_Enemy_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_Enemy_AnimGraphNode_TransitionResult_DD8F65FF423482C538A43999A4629F14");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Crab_AnimBP_Enemy.SK_Crab_AnimBP_Enemy_C.ExecuteUbergraph_SK_Crab_AnimBP_Enemy
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USK_Crab_AnimBP_Enemy_C::ExecuteUbergraph_SK_Crab_AnimBP_Enemy(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_Enemy_C", "ExecuteUbergraph_SK_Crab_AnimBP_Enemy");

	Params::SK_Crab_AnimBP_Enemy_C_ExecuteUbergraph_SK_Crab_AnimBP_Enemy Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

