#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SK_Crab_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function SK_Crab_AnimBP.SK_Crab_AnimBP_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct SK_Crab_AnimBP_C_AnimGraph final
{
public:
	struct FPoseLink                              Param_AnimGraph;                                   // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(SK_Crab_AnimBP_C_AnimGraph) == 0x000008, "Wrong alignment on SK_Crab_AnimBP_C_AnimGraph");
static_assert(sizeof(SK_Crab_AnimBP_C_AnimGraph) == 0x000010, "Wrong size on SK_Crab_AnimBP_C_AnimGraph");
static_assert(offsetof(SK_Crab_AnimBP_C_AnimGraph, Param_AnimGraph) == 0x000000, "Member 'SK_Crab_AnimBP_C_AnimGraph::Param_AnimGraph' has a wrong offset!");

// Function SK_Crab_AnimBP.SK_Crab_AnimBP_C.ExecuteUbergraph_SK_Crab_AnimBP
// 0x0024 (0x0024 - 0x0000)
struct SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_18D6[0x2];                                     // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRelevantAnimTime_ReturnValue;          // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_1;         // 0x000C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_18D7[0x3];                                     // 0x000D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_MapRangeClamped_ReturnValue;              // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Abs_ReturnValue;                          // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue_2;         // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_18D8[0x3];                                     // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_MapRangeClamped_ReturnValue_1;            // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_FloatFloat_ReturnValue;        // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP) == 0x000004, "Wrong alignment on SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP");
static_assert(sizeof(SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP) == 0x000024, "Wrong size on SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP");
static_assert(offsetof(SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP, EntryPoint) == 0x000000, "Member 'SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP::EntryPoint' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000004, "Member 'SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP, CallFunc_Less_FloatFloat_ReturnValue) == 0x000005, "Member 'SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP::CallFunc_Less_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP, CallFunc_GetRelevantAnimTime_ReturnValue) == 0x000008, "Member 'SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP::CallFunc_GetRelevantAnimTime_ReturnValue' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP, CallFunc_Greater_FloatFloat_ReturnValue_1) == 0x00000C, "Member 'SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP::CallFunc_Greater_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP, CallFunc_MapRangeClamped_ReturnValue) == 0x000010, "Member 'SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP::CallFunc_MapRangeClamped_ReturnValue' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP, CallFunc_Abs_ReturnValue) == 0x000014, "Member 'SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP::CallFunc_Abs_ReturnValue' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP, CallFunc_Greater_FloatFloat_ReturnValue_2) == 0x000018, "Member 'SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP::CallFunc_Greater_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP, CallFunc_MapRangeClamped_ReturnValue_1) == 0x00001C, "Member 'SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP::CallFunc_MapRangeClamped_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP, CallFunc_EqualEqual_FloatFloat_ReturnValue) == 0x000020, "Member 'SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP::CallFunc_EqualEqual_FloatFloat_ReturnValue' has a wrong offset!");

}

