#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SK_Crab_AnimBP

#include "Basic.hpp"

#include "SK_Crab_AnimBP_classes.hpp"
#include "SK_Crab_AnimBP_parameters.hpp"


namespace SDK
{

// Function SK_Crab_AnimBP.SK_Crab_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void USK_Crab_AnimBP_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_C", "AnimGraph");

	Params::SK_Crab_AnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function SK_Crab_AnimBP.SK_Crab_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_SequencePlayer_E4338ECD4DFB460BBB483D90B945E216
// (BlueprintEvent)

void USK_Crab_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_SequencePlayer_E4338ECD4DFB460BBB483D90B945E216()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_SequencePlayer_E4338ECD4DFB460BBB483D90B945E216");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Crab_AnimBP.SK_Crab_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_BlendListByBool_F9EDB7FF4B9502F7D00508A4D74B9E17
// (BlueprintEvent)

void USK_Crab_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_BlendListByBool_F9EDB7FF4B9502F7D00508A4D74B9E17()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_BlendListByBool_F9EDB7FF4B9502F7D00508A4D74B9E17");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Crab_AnimBP.SK_Crab_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_BlendListByBool_215BFAB940BF59D898CE37A086737F2C
// (BlueprintEvent)

void USK_Crab_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_BlendListByBool_215BFAB940BF59D898CE37A086737F2C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_BlendListByBool_215BFAB940BF59D898CE37A086737F2C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Crab_AnimBP.SK_Crab_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_SequencePlayer_8A3305B64CED6F9D8144E2810FB6882B
// (BlueprintEvent)

void USK_Crab_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_SequencePlayer_8A3305B64CED6F9D8144E2810FB6882B()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_SequencePlayer_8A3305B64CED6F9D8144E2810FB6882B");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Crab_AnimBP.SK_Crab_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_BlendSpacePlayer_E8712BEA4EC181C68A67D982FE6AFF10
// (BlueprintEvent)

void USK_Crab_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_BlendSpacePlayer_E8712BEA4EC181C68A67D982FE6AFF10()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_BlendSpacePlayer_E8712BEA4EC181C68A67D982FE6AFF10");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Crab_AnimBP.SK_Crab_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_TransitionResult_8E73A0074ECF2D7C189700A6EE5C4073
// (BlueprintEvent)

void USK_Crab_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_TransitionResult_8E73A0074ECF2D7C189700A6EE5C4073()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_TransitionResult_8E73A0074ECF2D7C189700A6EE5C4073");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Crab_AnimBP.SK_Crab_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_TransitionResult_0C5BFD424317F869BA9BA6952183128F
// (BlueprintEvent)

void USK_Crab_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_TransitionResult_0C5BFD424317F869BA9BA6952183128F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_TransitionResult_0C5BFD424317F869BA9BA6952183128F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Crab_AnimBP.SK_Crab_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_TransitionResult_C7DA0A2F42AA72E8164827BDEF0F70EC
// (BlueprintEvent)

void USK_Crab_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_TransitionResult_C7DA0A2F42AA72E8164827BDEF0F70EC()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Crab_AnimBP_AnimGraphNode_TransitionResult_C7DA0A2F42AA72E8164827BDEF0F70EC");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Crab_AnimBP.SK_Crab_AnimBP_C.ExecuteUbergraph_SK_Crab_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USK_Crab_AnimBP_C::ExecuteUbergraph_SK_Crab_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Crab_AnimBP_C", "ExecuteUbergraph_SK_Crab_AnimBP");

	Params::SK_Crab_AnimBP_C_ExecuteUbergraph_SK_Crab_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

