#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SK_Grub_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function SK_Grub_AnimBP.SK_Grub_AnimBP_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct SK_Grub_AnimBP_C_AnimGraph final
{
public:
	struct FPoseLink                              Param_AnimGraph;                                   // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(SK_Grub_AnimBP_C_AnimGraph) == 0x000008, "Wrong alignment on SK_Grub_AnimBP_C_AnimGraph");
static_assert(sizeof(SK_Grub_AnimBP_C_AnimGraph) == 0x000010, "Wrong size on SK_Grub_AnimBP_C_AnimGraph");
static_assert(offsetof(SK_Grub_AnimBP_C_AnimGraph, Param_AnimGraph) == 0x000000, "Member 'SK_Grub_AnimBP_C_AnimGraph::Param_AnimGraph' has a wrong offset!");

// Function SK_Grub_AnimBP.SK_Grub_AnimBP_C.ExecuteUbergraph_SK_Grub_AnimBP
// 0x0004 (0x0004 - 0x0000)
struct SK_Grub_AnimBP_C_ExecuteUbergraph_SK_Grub_AnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SK_Grub_AnimBP_C_ExecuteUbergraph_SK_Grub_AnimBP) == 0x000004, "Wrong alignment on SK_Grub_AnimBP_C_ExecuteUbergraph_SK_Grub_AnimBP");
static_assert(sizeof(SK_Grub_AnimBP_C_ExecuteUbergraph_SK_Grub_AnimBP) == 0x000004, "Wrong size on SK_Grub_AnimBP_C_ExecuteUbergraph_SK_Grub_AnimBP");
static_assert(offsetof(SK_Grub_AnimBP_C_ExecuteUbergraph_SK_Grub_AnimBP, EntryPoint) == 0x000000, "Member 'SK_Grub_AnimBP_C_ExecuteUbergraph_SK_Grub_AnimBP::EntryPoint' has a wrong offset!");

}

