#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SK_Grub_AnimBP

#include "Basic.hpp"

#include "SK_Grub_AnimBP_classes.hpp"
#include "SK_Grub_AnimBP_parameters.hpp"


namespace SDK
{

// Function SK_Grub_AnimBP.SK_Grub_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void USK_Grub_AnimBP_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Grub_AnimBP_C", "AnimGraph");

	Params::SK_Grub_AnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function SK_Grub_AnimBP.SK_Grub_AnimBP_C.ExecuteUbergraph_SK_Grub_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USK_Grub_AnimBP_C::ExecuteUbergraph_SK_Grub_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Grub_AnimBP_C", "ExecuteUbergraph_SK_Grub_AnimBP");

	Params::SK_Grub_AnimBP_C_ExecuteUbergraph_SK_Grub_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

