#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SK_Limpet_AnimBP

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "CrabChampions_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass SK_Limpet_AnimBP.SK_Limpet_AnimBP_C
// 0x0100 (0x03E0 - 0x02E0)
class USK_Limpet_AnimBP_C final : public UCrabEnemyAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02E8(0x0030)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0318(0x0080)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x0398(0x0048)()

public:
	void AnimGraph(struct FPoseLink* Param_AnimGraph);
	void ExecuteUbergraph_SK_Limpet_AnimBP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SK_Limpet_AnimBP_C">();
	}
	static class USK_Limpet_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USK_Limpet_AnimBP_C>();
	}
};
static_assert(alignof(USK_Limpet_AnimBP_C) == 0x000010, "Wrong alignment on USK_Limpet_AnimBP_C");
static_assert(sizeof(USK_Limpet_AnimBP_C) == 0x0003E0, "Wrong size on USK_Limpet_AnimBP_C");
static_assert(offsetof(USK_Limpet_AnimBP_C, UberGraphFrame) == 0x0002E0, "Member 'USK_Limpet_AnimBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(USK_Limpet_AnimBP_C, AnimGraphNode_Root) == 0x0002E8, "Member 'USK_Limpet_AnimBP_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(USK_Limpet_AnimBP_C, AnimGraphNode_SequencePlayer) == 0x000318, "Member 'USK_Limpet_AnimBP_C::AnimGraphNode_SequencePlayer' has a wrong offset!");
static_assert(offsetof(USK_Limpet_AnimBP_C, AnimGraphNode_Slot) == 0x000398, "Member 'USK_Limpet_AnimBP_C::AnimGraphNode_Slot' has a wrong offset!");

}

