#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SK_Starfish_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function SK_Starfish_AnimBP.SK_Starfish_AnimBP_C.ExecuteUbergraph_SK_Starfish_AnimBP
// 0x0008 (0x0008 - 0x0000)
struct SK_Starfish_AnimBP_C_ExecuteUbergraph_SK_Starfish_AnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(SK_Starfish_AnimBP_C_ExecuteUbergraph_SK_Starfish_AnimBP) == 0x000004, "Wrong alignment on SK_Starfish_AnimBP_C_ExecuteUbergraph_SK_Starfish_AnimBP");
static_assert(sizeof(SK_Starfish_AnimBP_C_ExecuteUbergraph_SK_Starfish_AnimBP) == 0x000008, "Wrong size on SK_Starfish_AnimBP_C_ExecuteUbergraph_SK_Starfish_AnimBP");
static_assert(offsetof(SK_Starfish_AnimBP_C_ExecuteUbergraph_SK_Starfish_AnimBP, EntryPoint) == 0x000000, "Member 'SK_Starfish_AnimBP_C_ExecuteUbergraph_SK_Starfish_AnimBP::EntryPoint' has a wrong offset!");
static_assert(offsetof(SK_Starfish_AnimBP_C_ExecuteUbergraph_SK_Starfish_AnimBP, CallFunc_Less_FloatFloat_ReturnValue) == 0x000004, "Member 'SK_Starfish_AnimBP_C_ExecuteUbergraph_SK_Starfish_AnimBP::CallFunc_Less_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(SK_Starfish_AnimBP_C_ExecuteUbergraph_SK_Starfish_AnimBP, CallFunc_Greater_FloatFloat_ReturnValue) == 0x000005, "Member 'SK_Starfish_AnimBP_C_ExecuteUbergraph_SK_Starfish_AnimBP::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");

// Function SK_Starfish_AnimBP.SK_Starfish_AnimBP_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct SK_Starfish_AnimBP_C_AnimGraph final
{
public:
	struct FPoseLink                              Param_AnimGraph;                                   // 0x0000(0x0010)(Parm, OutParm, NoDestructor)
};
static_assert(alignof(SK_Starfish_AnimBP_C_AnimGraph) == 0x000008, "Wrong alignment on SK_Starfish_AnimBP_C_AnimGraph");
static_assert(sizeof(SK_Starfish_AnimBP_C_AnimGraph) == 0x000010, "Wrong size on SK_Starfish_AnimBP_C_AnimGraph");
static_assert(offsetof(SK_Starfish_AnimBP_C_AnimGraph, Param_AnimGraph) == 0x000000, "Member 'SK_Starfish_AnimBP_C_AnimGraph::Param_AnimGraph' has a wrong offset!");

}

