#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SK_Scorpion_AnimBP

#include "Basic.hpp"

#include "SK_Scorpion_AnimBP_classes.hpp"
#include "SK_Scorpion_AnimBP_parameters.hpp"


namespace SDK
{

// Function SK_Scorpion_AnimBP.SK_Scorpion_AnimBP_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        Param_AnimGraph                                        (Parm, OutParm, NoDestructor)

void USK_Scorpion_AnimBP_C::AnimGraph(struct FPoseLink* Param_AnimGraph)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Scorpion_AnimBP_C", "AnimGraph");

	Params::SK_Scorpion_AnimBP_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_AnimGraph != nullptr)
		*Param_AnimGraph = std::move(Parms.Param_AnimGraph);
}


// Function SK_Scorpion_AnimBP.SK_Scorpion_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Scorpion_AnimBP_AnimGraphNode_SequencePlayer_81B11FE0473C7E04DDCD4B928EC21D15
// (BlueprintEvent)

void USK_Scorpion_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Scorpion_AnimBP_AnimGraphNode_SequencePlayer_81B11FE0473C7E04DDCD4B928EC21D15()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Scorpion_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Scorpion_AnimBP_AnimGraphNode_SequencePlayer_81B11FE0473C7E04DDCD4B928EC21D15");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Scorpion_AnimBP.SK_Scorpion_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Scorpion_AnimBP_AnimGraphNode_TransitionResult_9A6A4C6043634A4C16C73B9CFE25A885
// (BlueprintEvent)

void USK_Scorpion_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Scorpion_AnimBP_AnimGraphNode_TransitionResult_9A6A4C6043634A4C16C73B9CFE25A885()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Scorpion_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Scorpion_AnimBP_AnimGraphNode_TransitionResult_9A6A4C6043634A4C16C73B9CFE25A885");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Scorpion_AnimBP.SK_Scorpion_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Scorpion_AnimBP_AnimGraphNode_TransitionResult_D0D877C7403DFA7C45B163A28761A69D
// (BlueprintEvent)

void USK_Scorpion_AnimBP_C::EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Scorpion_AnimBP_AnimGraphNode_TransitionResult_D0D877C7403DFA7C45B163A28761A69D()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Scorpion_AnimBP_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_SK_Scorpion_AnimBP_AnimGraphNode_TransitionResult_D0D877C7403DFA7C45B163A28761A69D");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SK_Scorpion_AnimBP.SK_Scorpion_AnimBP_C.ExecuteUbergraph_SK_Scorpion_AnimBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USK_Scorpion_AnimBP_C::ExecuteUbergraph_SK_Scorpion_AnimBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SK_Scorpion_AnimBP_C", "ExecuteUbergraph_SK_Scorpion_AnimBP");

	Params::SK_Scorpion_AnimBP_C_ExecuteUbergraph_SK_Scorpion_AnimBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

