#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ArrowSelection

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_ArrowSelection.UI_ArrowSelection_C
// 0x0000 (0x0308 - 0x0308)
class UUI_ArrowSelection_C final : public UCrabArrowSelectionUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_ArrowSelection_C">();
	}
	static class UUI_ArrowSelection_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_ArrowSelection_C>();
	}
};
static_assert(alignof(UUI_ArrowSelection_C) == 0x000008, "Wrong alignment on UUI_ArrowSelection_C");
static_assert(sizeof(UUI_ArrowSelection_C) == 0x000308, "Wrong size on UUI_ArrowSelection_C");

}

