#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ChatEntryRow_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_ChatEntryRow_OLD.UI_ChatEntryRow_OLD_C
// 0x0000 (0x02C8 - 0x02C8)
class UUI_ChatEntryRow_OLD_C final : public UCrabChatEntryRowUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_ChatEntryRow_OLD_C">();
	}
	static class UUI_ChatEntryRow_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_ChatEntryRow_OLD_C>();
	}
};
static_assert(alignof(UUI_ChatEntryRow_OLD_C) == 0x000008, "Wrong alignment on UUI_ChatEntryRow_OLD_C");
static_assert(sizeof(UUI_ChatEntryRow_OLD_C) == 0x0002C8, "Wrong size on UUI_ChatEntryRow_OLD_C");

}

