#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ControlsMenu

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_ControlsMenu.UI_ControlsMenu_C
// 0x0018 (0x0330 - 0x0318)
class UUI_ControlsMenu_C final : public UCrabControlsMenuUI
{
public:
	class UUI_KeyBindRow_C*                       UI_KeyBindRow;                                     // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_KeyBindRow_C*                       UI_KeyBindRow_216;                                 // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_KeyBindRow_C*                       UI_KeyBindRow_504;                                 // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_ControlsMenu_C">();
	}
	static class UUI_ControlsMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_ControlsMenu_C>();
	}
};
static_assert(alignof(UUI_ControlsMenu_C) == 0x000008, "Wrong alignment on UUI_ControlsMenu_C");
static_assert(sizeof(UUI_ControlsMenu_C) == 0x000330, "Wrong size on UUI_ControlsMenu_C");
static_assert(offsetof(UUI_ControlsMenu_C, UI_KeyBindRow) == 0x000318, "Member 'UUI_ControlsMenu_C::UI_KeyBindRow' has a wrong offset!");
static_assert(offsetof(UUI_ControlsMenu_C, UI_KeyBindRow_216) == 0x000320, "Member 'UUI_ControlsMenu_C::UI_KeyBindRow_216' has a wrong offset!");
static_assert(offsetof(UUI_ControlsMenu_C, UI_KeyBindRow_504) == 0x000328, "Member 'UUI_ControlsMenu_C::UI_KeyBindRow_504' has a wrong offset!");

}

