#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Crosshair

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Crosshair.UI_Crosshair_C
// 0x0010 (0x0320 - 0x0310)
class UUI_Crosshair_C final : public UCrabCrosshairUI
{
public:
	class UImage*                                 EliminationHitmarkerImage;                         // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 EliminationImage;                                  // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Crosshair_C">();
	}
	static class UUI_Crosshair_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Crosshair_C>();
	}
};
static_assert(alignof(UUI_Crosshair_C) == 0x000008, "Wrong alignment on UUI_Crosshair_C");
static_assert(sizeof(UUI_Crosshair_C) == 0x000320, "Wrong size on UUI_Crosshair_C");
static_assert(offsetof(UUI_Crosshair_C, EliminationHitmarkerImage) == 0x000310, "Member 'UUI_Crosshair_C::EliminationHitmarkerImage' has a wrong offset!");
static_assert(offsetof(UUI_Crosshair_C, EliminationImage) == 0x000318, "Member 'UUI_Crosshair_C::EliminationImage' has a wrong offset!");

}

