#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_CosmeticsMenu_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_CosmeticsMenu_OLD.UI_CosmeticsMenu_OLD_C
// 0x0050 (0x0478 - 0x0428)
class UUI_CosmeticsMenu_OLD_C final : public UCrabCosmeticsMenuUI
{
public:
	class UImage*                                 Image_109;                                         // 0x0428(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CosmeticSlot_C*                     UI_UnlockableSlot;                                 // 0x0430(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CosmeticSlot_C*                     UI_UnlockableSlot_1;                               // 0x0438(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CosmeticSlot_C*                     UI_UnlockableSlot_2;                               // 0x0440(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CosmeticSlot_C*                     UI_UnlockableSlot_3;                               // 0x0448(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CosmeticSlot_C*                     UI_UnlockableSlot_4;                               // 0x0450(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CosmeticSlot_C*                     UI_UnlockableSlot_5;                               // 0x0458(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CosmeticSlot_C*                     UI_UnlockableSlot_6;                               // 0x0460(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CosmeticSlot_C*                     UI_UnlockableSlot_7;                               // 0x0468(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_CosmeticSlot_C*                     UI_UnlockableSlot_464;                             // 0x0470(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_CosmeticsMenu_OLD_C">();
	}
	static class UUI_CosmeticsMenu_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_CosmeticsMenu_OLD_C>();
	}
};
static_assert(alignof(UUI_CosmeticsMenu_OLD_C) == 0x000008, "Wrong alignment on UUI_CosmeticsMenu_OLD_C");
static_assert(sizeof(UUI_CosmeticsMenu_OLD_C) == 0x000478, "Wrong size on UUI_CosmeticsMenu_OLD_C");
static_assert(offsetof(UUI_CosmeticsMenu_OLD_C, Image_109) == 0x000428, "Member 'UUI_CosmeticsMenu_OLD_C::Image_109' has a wrong offset!");
static_assert(offsetof(UUI_CosmeticsMenu_OLD_C, UI_UnlockableSlot) == 0x000430, "Member 'UUI_CosmeticsMenu_OLD_C::UI_UnlockableSlot' has a wrong offset!");
static_assert(offsetof(UUI_CosmeticsMenu_OLD_C, UI_UnlockableSlot_1) == 0x000438, "Member 'UUI_CosmeticsMenu_OLD_C::UI_UnlockableSlot_1' has a wrong offset!");
static_assert(offsetof(UUI_CosmeticsMenu_OLD_C, UI_UnlockableSlot_2) == 0x000440, "Member 'UUI_CosmeticsMenu_OLD_C::UI_UnlockableSlot_2' has a wrong offset!");
static_assert(offsetof(UUI_CosmeticsMenu_OLD_C, UI_UnlockableSlot_3) == 0x000448, "Member 'UUI_CosmeticsMenu_OLD_C::UI_UnlockableSlot_3' has a wrong offset!");
static_assert(offsetof(UUI_CosmeticsMenu_OLD_C, UI_UnlockableSlot_4) == 0x000450, "Member 'UUI_CosmeticsMenu_OLD_C::UI_UnlockableSlot_4' has a wrong offset!");
static_assert(offsetof(UUI_CosmeticsMenu_OLD_C, UI_UnlockableSlot_5) == 0x000458, "Member 'UUI_CosmeticsMenu_OLD_C::UI_UnlockableSlot_5' has a wrong offset!");
static_assert(offsetof(UUI_CosmeticsMenu_OLD_C, UI_UnlockableSlot_6) == 0x000460, "Member 'UUI_CosmeticsMenu_OLD_C::UI_UnlockableSlot_6' has a wrong offset!");
static_assert(offsetof(UUI_CosmeticsMenu_OLD_C, UI_UnlockableSlot_7) == 0x000468, "Member 'UUI_CosmeticsMenu_OLD_C::UI_UnlockableSlot_7' has a wrong offset!");
static_assert(offsetof(UUI_CosmeticsMenu_OLD_C, UI_UnlockableSlot_464) == 0x000470, "Member 'UUI_CosmeticsMenu_OLD_C::UI_UnlockableSlot_464' has a wrong offset!");

}

