#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_DifficultyMenu_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_DifficultyMenu_OLD.UI_DifficultyMenu_OLD_C
// 0x0078 (0x04C8 - 0x0450)
class UUI_DifficultyMenu_OLD_C final : public UCrabDifficultyMenuUI
{
public:
	class UImage*                                 BackgroundDarken;                                  // 0x0450(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BackgroundDarken_1;                                // 0x0458(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x0460(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_1;                                           // 0x0468(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x0470(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_3;                                           // 0x0478(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_4;                                           // 0x0480(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_5;                                           // 0x0488(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_6;                                           // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_7;                                           // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_8;                                           // 0x04A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_9;                                           // 0x04A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_124;                                         // 0x04B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_138;                                         // 0x04B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_DifficultyModifier_C*               UI_DifficultyModifier;                             // 0x04C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_DifficultyMenu_OLD_C">();
	}
	static class UUI_DifficultyMenu_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_DifficultyMenu_OLD_C>();
	}
};
static_assert(alignof(UUI_DifficultyMenu_OLD_C) == 0x000008, "Wrong alignment on UUI_DifficultyMenu_OLD_C");
static_assert(sizeof(UUI_DifficultyMenu_OLD_C) == 0x0004C8, "Wrong size on UUI_DifficultyMenu_OLD_C");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, BackgroundDarken) == 0x000450, "Member 'UUI_DifficultyMenu_OLD_C::BackgroundDarken' has a wrong offset!");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, BackgroundDarken_1) == 0x000458, "Member 'UUI_DifficultyMenu_OLD_C::BackgroundDarken_1' has a wrong offset!");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, Image) == 0x000460, "Member 'UUI_DifficultyMenu_OLD_C::Image' has a wrong offset!");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, Image_1) == 0x000468, "Member 'UUI_DifficultyMenu_OLD_C::Image_1' has a wrong offset!");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, Image_2) == 0x000470, "Member 'UUI_DifficultyMenu_OLD_C::Image_2' has a wrong offset!");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, Image_3) == 0x000478, "Member 'UUI_DifficultyMenu_OLD_C::Image_3' has a wrong offset!");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, Image_4) == 0x000480, "Member 'UUI_DifficultyMenu_OLD_C::Image_4' has a wrong offset!");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, Image_5) == 0x000488, "Member 'UUI_DifficultyMenu_OLD_C::Image_5' has a wrong offset!");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, Image_6) == 0x000490, "Member 'UUI_DifficultyMenu_OLD_C::Image_6' has a wrong offset!");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, Image_7) == 0x000498, "Member 'UUI_DifficultyMenu_OLD_C::Image_7' has a wrong offset!");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, Image_8) == 0x0004A0, "Member 'UUI_DifficultyMenu_OLD_C::Image_8' has a wrong offset!");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, Image_9) == 0x0004A8, "Member 'UUI_DifficultyMenu_OLD_C::Image_9' has a wrong offset!");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, Image_124) == 0x0004B0, "Member 'UUI_DifficultyMenu_OLD_C::Image_124' has a wrong offset!");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, Image_138) == 0x0004B8, "Member 'UUI_DifficultyMenu_OLD_C::Image_138' has a wrong offset!");
static_assert(offsetof(UUI_DifficultyMenu_OLD_C, UI_DifficultyModifier) == 0x0004C0, "Member 'UUI_DifficultyMenu_OLD_C::UI_DifficultyModifier' has a wrong offset!");

}

