#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_GameOverRow

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_GameOverRow.UI_GameOverRow_C
// 0x0000 (0x02F0 - 0x02F0)
class UUI_GameOverRow_C final : public UCrabGameOverRowUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_GameOverRow_C">();
	}
	static class UUI_GameOverRow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_GameOverRow_C>();
	}
};
static_assert(alignof(UUI_GameOverRow_C) == 0x000008, "Wrong alignment on UUI_GameOverRow_C");
static_assert(sizeof(UUI_GameOverRow_C) == 0x0002F0, "Wrong size on UUI_GameOverRow_C");

}

