#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Gameplay_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Gameplay_OLD.UI_Gameplay_OLD_C
// 0x0038 (0x0498 - 0x0460)
class UUI_Gameplay_OLD_C final : public UCrabGameplayUI
{
public:
	class UWidgetAnimation*                       LevelUpAnim;                                       // 0x0460(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       OnCharacterLandAnim;                               // 0x0468(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x0470(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_1;                                           // 0x0478(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_110;                                         // 0x0480(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_226;                                         // 0x0488(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TookDamageImage;                                   // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Gameplay_OLD_C">();
	}
	static class UUI_Gameplay_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Gameplay_OLD_C>();
	}
};
static_assert(alignof(UUI_Gameplay_OLD_C) == 0x000008, "Wrong alignment on UUI_Gameplay_OLD_C");
static_assert(sizeof(UUI_Gameplay_OLD_C) == 0x000498, "Wrong size on UUI_Gameplay_OLD_C");
static_assert(offsetof(UUI_Gameplay_OLD_C, LevelUpAnim) == 0x000460, "Member 'UUI_Gameplay_OLD_C::LevelUpAnim' has a wrong offset!");
static_assert(offsetof(UUI_Gameplay_OLD_C, OnCharacterLandAnim) == 0x000468, "Member 'UUI_Gameplay_OLD_C::OnCharacterLandAnim' has a wrong offset!");
static_assert(offsetof(UUI_Gameplay_OLD_C, Image) == 0x000470, "Member 'UUI_Gameplay_OLD_C::Image' has a wrong offset!");
static_assert(offsetof(UUI_Gameplay_OLD_C, Image_1) == 0x000478, "Member 'UUI_Gameplay_OLD_C::Image_1' has a wrong offset!");
static_assert(offsetof(UUI_Gameplay_OLD_C, Image_110) == 0x000480, "Member 'UUI_Gameplay_OLD_C::Image_110' has a wrong offset!");
static_assert(offsetof(UUI_Gameplay_OLD_C, Image_226) == 0x000488, "Member 'UUI_Gameplay_OLD_C::Image_226' has a wrong offset!");
static_assert(offsetof(UUI_Gameplay_OLD_C, TookDamageImage) == 0x000490, "Member 'UUI_Gameplay_OLD_C::TookDamageImage' has a wrong offset!");

}

