#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_GameOver_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_GameOver_OLD.UI_GameOver_OLD_C
// 0x0038 (0x04B0 - 0x0478)
class UUI_GameOver_OLD_C final : public UCrabGameOverUI
{
public:
	class UImage*                                 BackgroundDarken;                                  // 0x0478(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_GameOverRow_C*                      UI_Survival_GameOverRow;                           // 0x0480(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_GameOverRow_C*                      UI_Survival_GameOverRow_1;                         // 0x0488(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_GameOverRow_C*                      UI_Survival_GameOverRow_207;                       // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_GameOverRow_C*                      UI_Survival_GameOverRow_644;                       // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_UnlockedCosmetic_C*                 UI_UnlockableThumbnail;                            // 0x04A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_UnlockedCosmetic_C*                 UI_UnlockableThumbnail_1;                          // 0x04A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_GameOver_OLD_C">();
	}
	static class UUI_GameOver_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_GameOver_OLD_C>();
	}
};
static_assert(alignof(UUI_GameOver_OLD_C) == 0x000008, "Wrong alignment on UUI_GameOver_OLD_C");
static_assert(sizeof(UUI_GameOver_OLD_C) == 0x0004B0, "Wrong size on UUI_GameOver_OLD_C");
static_assert(offsetof(UUI_GameOver_OLD_C, BackgroundDarken) == 0x000478, "Member 'UUI_GameOver_OLD_C::BackgroundDarken' has a wrong offset!");
static_assert(offsetof(UUI_GameOver_OLD_C, UI_Survival_GameOverRow) == 0x000480, "Member 'UUI_GameOver_OLD_C::UI_Survival_GameOverRow' has a wrong offset!");
static_assert(offsetof(UUI_GameOver_OLD_C, UI_Survival_GameOverRow_1) == 0x000488, "Member 'UUI_GameOver_OLD_C::UI_Survival_GameOverRow_1' has a wrong offset!");
static_assert(offsetof(UUI_GameOver_OLD_C, UI_Survival_GameOverRow_207) == 0x000490, "Member 'UUI_GameOver_OLD_C::UI_Survival_GameOverRow_207' has a wrong offset!");
static_assert(offsetof(UUI_GameOver_OLD_C, UI_Survival_GameOverRow_644) == 0x000498, "Member 'UUI_GameOver_OLD_C::UI_Survival_GameOverRow_644' has a wrong offset!");
static_assert(offsetof(UUI_GameOver_OLD_C, UI_UnlockableThumbnail) == 0x0004A0, "Member 'UUI_GameOver_OLD_C::UI_UnlockableThumbnail' has a wrong offset!");
static_assert(offsetof(UUI_GameOver_OLD_C, UI_UnlockableThumbnail_1) == 0x0004A8, "Member 'UUI_GameOver_OLD_C::UI_UnlockableThumbnail_1' has a wrong offset!");

}

