#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_GameState_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_GameState_OLD.UI_GameState_OLD_C
// 0x0088 (0x04C8 - 0x0440)
class UUI_GameState_OLD_C final : public UCrabGameStateUI
{
public:
	class UImage*                                 BlackImage;                                        // 0x0440(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_4;                                           // 0x0448(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_6;                                           // 0x0450(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_8;                                           // 0x0458(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_9;                                           // 0x0460(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_10;                                          // 0x0468(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_11;                                          // 0x0470(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_12;                                          // 0x0478(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_13;                                          // 0x0480(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_14;                                          // 0x0488(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_15;                                          // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_16;                                          // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_17;                                          // 0x04A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_18;                                          // 0x04A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_27;                                          // 0x04B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_108;                                         // 0x04B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_226;                                         // 0x04C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_GameState_OLD_C">();
	}
	static class UUI_GameState_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_GameState_OLD_C>();
	}
};
static_assert(alignof(UUI_GameState_OLD_C) == 0x000008, "Wrong alignment on UUI_GameState_OLD_C");
static_assert(sizeof(UUI_GameState_OLD_C) == 0x0004C8, "Wrong size on UUI_GameState_OLD_C");
static_assert(offsetof(UUI_GameState_OLD_C, BlackImage) == 0x000440, "Member 'UUI_GameState_OLD_C::BlackImage' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_4) == 0x000448, "Member 'UUI_GameState_OLD_C::Image_4' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_6) == 0x000450, "Member 'UUI_GameState_OLD_C::Image_6' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_8) == 0x000458, "Member 'UUI_GameState_OLD_C::Image_8' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_9) == 0x000460, "Member 'UUI_GameState_OLD_C::Image_9' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_10) == 0x000468, "Member 'UUI_GameState_OLD_C::Image_10' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_11) == 0x000470, "Member 'UUI_GameState_OLD_C::Image_11' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_12) == 0x000478, "Member 'UUI_GameState_OLD_C::Image_12' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_13) == 0x000480, "Member 'UUI_GameState_OLD_C::Image_13' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_14) == 0x000488, "Member 'UUI_GameState_OLD_C::Image_14' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_15) == 0x000490, "Member 'UUI_GameState_OLD_C::Image_15' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_16) == 0x000498, "Member 'UUI_GameState_OLD_C::Image_16' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_17) == 0x0004A0, "Member 'UUI_GameState_OLD_C::Image_17' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_18) == 0x0004A8, "Member 'UUI_GameState_OLD_C::Image_18' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_27) == 0x0004B0, "Member 'UUI_GameState_OLD_C::Image_27' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_108) == 0x0004B8, "Member 'UUI_GameState_OLD_C::Image_108' has a wrong offset!");
static_assert(offsetof(UUI_GameState_OLD_C, Image_226) == 0x0004C0, "Member 'UUI_GameState_OLD_C::Image_226' has a wrong offset!");

}

