#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_InGameMenu_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_InGameMenu_OLD.UI_InGameMenu_OLD_C
// 0x0008 (0x0438 - 0x0430)
class UUI_InGameMenu_OLD_C final : public UCrabInGameMenuUI
{
public:
	class UImage*                                 BackgroundDarken;                                  // 0x0430(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_InGameMenu_OLD_C">();
	}
	static class UUI_InGameMenu_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_InGameMenu_OLD_C>();
	}
};
static_assert(alignof(UUI_InGameMenu_OLD_C) == 0x000008, "Wrong alignment on UUI_InGameMenu_OLD_C");
static_assert(sizeof(UUI_InGameMenu_OLD_C) == 0x000438, "Wrong size on UUI_InGameMenu_OLD_C");
static_assert(offsetof(UUI_InGameMenu_OLD_C, BackgroundDarken) == 0x000430, "Member 'UUI_InGameMenu_OLD_C::BackgroundDarken' has a wrong offset!");

}

