#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Interact_Portal

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Interact_Portal.UI_Interact_Portal_C
// 0x0028 (0x03E8 - 0x03C0)
class UUI_Interact_Portal_C final : public UCrabPortalInteractUI
{
public:
	class UImage*                                 IconImage_1;                                       // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IconImage_2;                                       // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IconImage_3;                                       // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 IconImage_4;                                       // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_310;                                         // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Interact_Portal_C">();
	}
	static class UUI_Interact_Portal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Interact_Portal_C>();
	}
};
static_assert(alignof(UUI_Interact_Portal_C) == 0x000008, "Wrong alignment on UUI_Interact_Portal_C");
static_assert(sizeof(UUI_Interact_Portal_C) == 0x0003E8, "Wrong size on UUI_Interact_Portal_C");
static_assert(offsetof(UUI_Interact_Portal_C, IconImage_1) == 0x0003C0, "Member 'UUI_Interact_Portal_C::IconImage_1' has a wrong offset!");
static_assert(offsetof(UUI_Interact_Portal_C, IconImage_2) == 0x0003C8, "Member 'UUI_Interact_Portal_C::IconImage_2' has a wrong offset!");
static_assert(offsetof(UUI_Interact_Portal_C, IconImage_3) == 0x0003D0, "Member 'UUI_Interact_Portal_C::IconImage_3' has a wrong offset!");
static_assert(offsetof(UUI_Interact_Portal_C, IconImage_4) == 0x0003D8, "Member 'UUI_Interact_Portal_C::IconImage_4' has a wrong offset!");
static_assert(offsetof(UUI_Interact_Portal_C, Image_310) == 0x0003E0, "Member 'UUI_Interact_Portal_C::Image_310' has a wrong offset!");

}

