#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_InventorySlot_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_InventorySlot_OLD.UI_InventorySlot_OLD_C
// 0x0008 (0x0328 - 0x0320)
class UUI_InventorySlot_OLD_C final : public UCrabInventorySlotUI
{
public:
	class UImage*                                 Image_133;                                         // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_InventorySlot_OLD_C">();
	}
	static class UUI_InventorySlot_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_InventorySlot_OLD_C>();
	}
};
static_assert(alignof(UUI_InventorySlot_OLD_C) == 0x000008, "Wrong alignment on UUI_InventorySlot_OLD_C");
static_assert(sizeof(UUI_InventorySlot_OLD_C) == 0x000328, "Wrong size on UUI_InventorySlot_OLD_C");
static_assert(offsetof(UUI_InventorySlot_OLD_C, Image_133) == 0x000320, "Member 'UUI_InventorySlot_OLD_C::Image_133' has a wrong offset!");

}

