#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_InventoryEvent

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_InventoryEvent.UI_InventoryEvent_C
// 0x0000 (0x02C8 - 0x02C8)
class UUI_InventoryEvent_C final : public UCrabInventoryEventUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_InventoryEvent_C">();
	}
	static class UUI_InventoryEvent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_InventoryEvent_C>();
	}
};
static_assert(alignof(UUI_InventoryEvent_C) == 0x000008, "Wrong alignment on UUI_InventoryEvent_C");
static_assert(sizeof(UUI_InventoryEvent_C) == 0x0002C8, "Wrong size on UUI_InventoryEvent_C");

}

