#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Inventory_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Inventory_OLD.UI_Inventory_OLD_C
// 0x0330 (0x0860 - 0x0530)
class UUI_Inventory_OLD_C final : public UCrabInventoryUI
{
public:
	class UImage*                                 BackgroundDarken;                                  // 0x0530(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BackgroundDarken_1;                                // 0x0538(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x0540(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_1;                                           // 0x0548(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x0550(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_3;                                           // 0x0558(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_4;                                           // 0x0560(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_5;                                           // 0x0568(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_6;                                           // 0x0570(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_7;                                           // 0x0578(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_8;                                           // 0x0580(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_9;                                           // 0x0588(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_10;                                          // 0x0590(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_11;                                          // 0x0598(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_12;                                          // 0x05A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_13;                                          // 0x05A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_14;                                          // 0x05B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_16;                                          // 0x05B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_17;                                          // 0x05C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_18;                                          // 0x05C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_19;                                          // 0x05D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_141;                                         // 0x05D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_310;                                         // 0x05E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TopDivider;                                        // 0x05E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot;                         // 0x05F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_1;                       // 0x05F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_2;                       // 0x0600(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_3;                       // 0x0608(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_4;                       // 0x0610(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_5;                       // 0x0618(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_6;                       // 0x0620(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_7;                       // 0x0628(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_8;                       // 0x0630(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_9;                       // 0x0638(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_10;                      // 0x0640(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_11;                      // 0x0648(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_12;                      // 0x0650(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_13;                      // 0x0658(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_14;                      // 0x0660(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_15;                      // 0x0668(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_16;                      // 0x0670(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_17;                      // 0x0678(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_18;                      // 0x0680(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_19;                      // 0x0688(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_20;                      // 0x0690(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_21;                      // 0x0698(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_22;                      // 0x06A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_23;                      // 0x06A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_24;                      // 0x06B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_25;                      // 0x06B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_26;                      // 0x06C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_27;                      // 0x06C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_28;                      // 0x06D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_29;                      // 0x06D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_30;                      // 0x06E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_31;                      // 0x06E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_32;                      // 0x06F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_33;                      // 0x06F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_34;                      // 0x0700(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_35;                      // 0x0708(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_36;                      // 0x0710(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_37;                      // 0x0718(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_38;                      // 0x0720(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_39;                      // 0x0728(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_40;                      // 0x0730(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_41;                      // 0x0738(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_42;                      // 0x0740(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_43;                      // 0x0748(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_44;                      // 0x0750(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_45;                      // 0x0758(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_46;                      // 0x0760(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_47;                      // 0x0768(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_48;                      // 0x0770(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_49;                      // 0x0778(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_50;                      // 0x0780(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_51;                      // 0x0788(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_52;                      // 0x0790(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_53;                      // 0x0798(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_54;                      // 0x07A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_55;                      // 0x07A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_56;                      // 0x07B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_57;                      // 0x07B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_58;                      // 0x07C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_59;                      // 0x07C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_60;                      // 0x07D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_61;                      // 0x07D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_62;                      // 0x07E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_63;                      // 0x07E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_64;                      // 0x07F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_65;                      // 0x07F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_66;                      // 0x0800(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_67;                      // 0x0808(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_68;                      // 0x0810(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_69;                      // 0x0818(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_70;                      // 0x0820(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_71;                      // 0x0828(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_72;                      // 0x0830(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_73;                      // 0x0838(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_74;                      // 0x0840(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_75;                      // 0x0848(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_76;                      // 0x0850(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InventorySlot_OLD_C*                UI_Survival_InventorySlot_437;                     // 0x0858(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Inventory_OLD_C">();
	}
	static class UUI_Inventory_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Inventory_OLD_C>();
	}
};
static_assert(alignof(UUI_Inventory_OLD_C) == 0x000008, "Wrong alignment on UUI_Inventory_OLD_C");
static_assert(sizeof(UUI_Inventory_OLD_C) == 0x000860, "Wrong size on UUI_Inventory_OLD_C");
static_assert(offsetof(UUI_Inventory_OLD_C, BackgroundDarken) == 0x000530, "Member 'UUI_Inventory_OLD_C::BackgroundDarken' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, BackgroundDarken_1) == 0x000538, "Member 'UUI_Inventory_OLD_C::BackgroundDarken_1' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image) == 0x000540, "Member 'UUI_Inventory_OLD_C::Image' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_1) == 0x000548, "Member 'UUI_Inventory_OLD_C::Image_1' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_2) == 0x000550, "Member 'UUI_Inventory_OLD_C::Image_2' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_3) == 0x000558, "Member 'UUI_Inventory_OLD_C::Image_3' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_4) == 0x000560, "Member 'UUI_Inventory_OLD_C::Image_4' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_5) == 0x000568, "Member 'UUI_Inventory_OLD_C::Image_5' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_6) == 0x000570, "Member 'UUI_Inventory_OLD_C::Image_6' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_7) == 0x000578, "Member 'UUI_Inventory_OLD_C::Image_7' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_8) == 0x000580, "Member 'UUI_Inventory_OLD_C::Image_8' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_9) == 0x000588, "Member 'UUI_Inventory_OLD_C::Image_9' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_10) == 0x000590, "Member 'UUI_Inventory_OLD_C::Image_10' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_11) == 0x000598, "Member 'UUI_Inventory_OLD_C::Image_11' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_12) == 0x0005A0, "Member 'UUI_Inventory_OLD_C::Image_12' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_13) == 0x0005A8, "Member 'UUI_Inventory_OLD_C::Image_13' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_14) == 0x0005B0, "Member 'UUI_Inventory_OLD_C::Image_14' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_16) == 0x0005B8, "Member 'UUI_Inventory_OLD_C::Image_16' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_17) == 0x0005C0, "Member 'UUI_Inventory_OLD_C::Image_17' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_18) == 0x0005C8, "Member 'UUI_Inventory_OLD_C::Image_18' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_19) == 0x0005D0, "Member 'UUI_Inventory_OLD_C::Image_19' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_141) == 0x0005D8, "Member 'UUI_Inventory_OLD_C::Image_141' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, Image_310) == 0x0005E0, "Member 'UUI_Inventory_OLD_C::Image_310' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, TopDivider) == 0x0005E8, "Member 'UUI_Inventory_OLD_C::TopDivider' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot) == 0x0005F0, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_1) == 0x0005F8, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_1' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_2) == 0x000600, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_2' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_3) == 0x000608, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_3' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_4) == 0x000610, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_4' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_5) == 0x000618, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_5' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_6) == 0x000620, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_6' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_7) == 0x000628, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_7' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_8) == 0x000630, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_8' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_9) == 0x000638, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_9' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_10) == 0x000640, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_10' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_11) == 0x000648, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_11' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_12) == 0x000650, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_12' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_13) == 0x000658, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_13' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_14) == 0x000660, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_14' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_15) == 0x000668, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_15' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_16) == 0x000670, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_16' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_17) == 0x000678, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_17' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_18) == 0x000680, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_18' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_19) == 0x000688, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_19' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_20) == 0x000690, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_20' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_21) == 0x000698, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_21' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_22) == 0x0006A0, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_22' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_23) == 0x0006A8, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_23' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_24) == 0x0006B0, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_24' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_25) == 0x0006B8, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_25' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_26) == 0x0006C0, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_26' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_27) == 0x0006C8, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_27' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_28) == 0x0006D0, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_28' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_29) == 0x0006D8, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_29' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_30) == 0x0006E0, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_30' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_31) == 0x0006E8, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_31' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_32) == 0x0006F0, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_32' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_33) == 0x0006F8, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_33' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_34) == 0x000700, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_34' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_35) == 0x000708, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_35' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_36) == 0x000710, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_36' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_37) == 0x000718, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_37' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_38) == 0x000720, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_38' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_39) == 0x000728, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_39' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_40) == 0x000730, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_40' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_41) == 0x000738, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_41' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_42) == 0x000740, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_42' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_43) == 0x000748, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_43' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_44) == 0x000750, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_44' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_45) == 0x000758, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_45' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_46) == 0x000760, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_46' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_47) == 0x000768, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_47' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_48) == 0x000770, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_48' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_49) == 0x000778, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_49' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_50) == 0x000780, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_50' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_51) == 0x000788, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_51' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_52) == 0x000790, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_52' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_53) == 0x000798, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_53' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_54) == 0x0007A0, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_54' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_55) == 0x0007A8, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_55' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_56) == 0x0007B0, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_56' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_57) == 0x0007B8, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_57' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_58) == 0x0007C0, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_58' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_59) == 0x0007C8, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_59' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_60) == 0x0007D0, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_60' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_61) == 0x0007D8, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_61' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_62) == 0x0007E0, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_62' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_63) == 0x0007E8, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_63' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_64) == 0x0007F0, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_64' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_65) == 0x0007F8, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_65' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_66) == 0x000800, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_66' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_67) == 0x000808, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_67' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_68) == 0x000810, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_68' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_69) == 0x000818, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_69' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_70) == 0x000820, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_70' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_71) == 0x000828, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_71' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_72) == 0x000830, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_72' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_73) == 0x000838, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_73' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_74) == 0x000840, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_74' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_75) == 0x000848, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_75' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_76) == 0x000850, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_76' has a wrong offset!");
static_assert(offsetof(UUI_Inventory_OLD_C, UI_Survival_InventorySlot_437) == 0x000858, "Member 'UUI_Inventory_OLD_C::UI_Survival_InventorySlot_437' has a wrong offset!");

}

