#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_InviteFriendRow

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_InviteFriendRow.UI_InviteFriendRow_C
// 0x0000 (0x02E8 - 0x02E8)
class UUI_InviteFriendRow_C final : public UCrabInviteFriendRowUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_InviteFriendRow_C">();
	}
	static class UUI_InviteFriendRow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_InviteFriendRow_C>();
	}
};
static_assert(alignof(UUI_InviteFriendRow_C) == 0x000008, "Wrong alignment on UUI_InviteFriendRow_C");
static_assert(sizeof(UUI_InviteFriendRow_C) == 0x0002E8, "Wrong size on UUI_InviteFriendRow_C");

}

