#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_JoinedPlayerRow

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_JoinedPlayerRow.UI_JoinedPlayerRow_C
// 0x0000 (0x02C8 - 0x02C8)
class UUI_JoinedPlayerRow_C final : public UCrabJoinedPlayerRowUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_JoinedPlayerRow_C">();
	}
	static class UUI_JoinedPlayerRow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_JoinedPlayerRow_C>();
	}
};
static_assert(alignof(UUI_JoinedPlayerRow_C) == 0x000008, "Wrong alignment on UUI_JoinedPlayerRow_C");
static_assert(sizeof(UUI_JoinedPlayerRow_C) == 0x0002C8, "Wrong size on UUI_JoinedPlayerRow_C");

}

