#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_KeyBindRow

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_KeyBindRow.UI_KeyBindRow_C
// 0x0000 (0x0360 - 0x0360)
class UUI_KeyBindRow_C final : public UCrabKeyBindRowUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_KeyBindRow_C">();
	}
	static class UUI_KeyBindRow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_KeyBindRow_C>();
	}
};
static_assert(alignof(UUI_KeyBindRow_C) == 0x000008, "Wrong alignment on UUI_KeyBindRow_C");
static_assert(sizeof(UUI_KeyBindRow_C) == 0x000360, "Wrong size on UUI_KeyBindRow_C");

}

