#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Location

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Location.UI_Location_C
// 0x0000 (0x0260 - 0x0260)
class UUI_Location_C final : public UUserWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Location_C">();
	}
	static class UUI_Location_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Location_C>();
	}
};
static_assert(alignof(UUI_Location_C) == 0x000008, "Wrong alignment on UUI_Location_C");
static_assert(sizeof(UUI_Location_C) == 0x000260, "Wrong size on UUI_Location_C");

}

