#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_MinigameGameOver

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_MinigameGameOver.UI_MinigameGameOver_C
// 0x0030 (0x0430 - 0x0400)
class UUI_MinigameGameOver_C final : public UCrabMinigameGameOverUI
{
public:
	class UImage*                                 BackgroundDarken;                                  // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_MinigameGameOverRow_C*              UI_MinigameGameOverRow;                            // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_MinigameGameOverRow_C*              UI_MinigameGameOverRow_101;                        // 0x0410(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_MinigameGameOverRow_C*              UI_MinigameGameOverRow_218;                        // 0x0418(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_MinigameGameOverRow_C*              UI_MinigameGameOverRow_319;                        // 0x0420(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_MinigameGameOverRow_C*              UI_MinigameGameOverRow_596;                        // 0x0428(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_MinigameGameOver_C">();
	}
	static class UUI_MinigameGameOver_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_MinigameGameOver_C>();
	}
};
static_assert(alignof(UUI_MinigameGameOver_C) == 0x000008, "Wrong alignment on UUI_MinigameGameOver_C");
static_assert(sizeof(UUI_MinigameGameOver_C) == 0x000430, "Wrong size on UUI_MinigameGameOver_C");
static_assert(offsetof(UUI_MinigameGameOver_C, BackgroundDarken) == 0x000400, "Member 'UUI_MinigameGameOver_C::BackgroundDarken' has a wrong offset!");
static_assert(offsetof(UUI_MinigameGameOver_C, UI_MinigameGameOverRow) == 0x000408, "Member 'UUI_MinigameGameOver_C::UI_MinigameGameOverRow' has a wrong offset!");
static_assert(offsetof(UUI_MinigameGameOver_C, UI_MinigameGameOverRow_101) == 0x000410, "Member 'UUI_MinigameGameOver_C::UI_MinigameGameOverRow_101' has a wrong offset!");
static_assert(offsetof(UUI_MinigameGameOver_C, UI_MinigameGameOverRow_218) == 0x000418, "Member 'UUI_MinigameGameOver_C::UI_MinigameGameOverRow_218' has a wrong offset!");
static_assert(offsetof(UUI_MinigameGameOver_C, UI_MinigameGameOverRow_319) == 0x000420, "Member 'UUI_MinigameGameOver_C::UI_MinigameGameOverRow_319' has a wrong offset!");
static_assert(offsetof(UUI_MinigameGameOver_C, UI_MinigameGameOverRow_596) == 0x000428, "Member 'UUI_MinigameGameOver_C::UI_MinigameGameOverRow_596' has a wrong offset!");

}

