#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_MinigameGameOverRow

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_MinigameGameOverRow.UI_MinigameGameOverRow_C
// 0x0000 (0x02D8 - 0x02D8)
class UUI_MinigameGameOverRow_C final : public UCrabMinigameGameOverRowUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_MinigameGameOverRow_C">();
	}
	static class UUI_MinigameGameOverRow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_MinigameGameOverRow_C>();
	}
};
static_assert(alignof(UUI_MinigameGameOverRow_C) == 0x000008, "Wrong alignment on UUI_MinigameGameOverRow_C");
static_assert(sizeof(UUI_MinigameGameOverRow_C) == 0x0002D8, "Wrong size on UUI_MinigameGameOverRow_C");

}

