#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_MultiplayerMenu_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_MultiplayerMenu_OLD.UI_MultiplayerMenu_OLD_C
// 0x00E0 (0x04E8 - 0x0408)
class UUI_MultiplayerMenu_OLD_C final : public UCrabMultiplayerMenuUI
{
public:
	class UImage*                                 BackgroundDarken;                                  // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow;                                 // 0x0410(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_1;                               // 0x0418(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_2;                               // 0x0420(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_3;                               // 0x0428(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_4;                               // 0x0430(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_5;                               // 0x0438(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_6;                               // 0x0440(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_7;                               // 0x0448(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_8;                               // 0x0450(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_9;                               // 0x0458(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_10;                              // 0x0460(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_11;                              // 0x0468(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_12;                              // 0x0470(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_13;                              // 0x0478(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_14;                              // 0x0480(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_15;                              // 0x0488(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_16;                              // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_17;                              // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_18;                              // 0x04A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_19;                              // 0x04A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_20;                              // 0x04B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_161;                             // 0x04B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_InviteFriendRow_C*                  UI_LobbyFriendRow_293;                             // 0x04C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_JoinedPlayerRow_C*                  UI_LobbyPlayerRow;                                 // 0x04C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_JoinedPlayerRow_C*                  UI_LobbyPlayerRow_1;                               // 0x04D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_JoinedPlayerRow_C*                  UI_LobbyPlayerRow_118;                             // 0x04D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_JoinedPlayerRow_C*                  UI_LobbyPlayerRow_252;                             // 0x04E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_MultiplayerMenu_OLD_C">();
	}
	static class UUI_MultiplayerMenu_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_MultiplayerMenu_OLD_C>();
	}
};
static_assert(alignof(UUI_MultiplayerMenu_OLD_C) == 0x000008, "Wrong alignment on UUI_MultiplayerMenu_OLD_C");
static_assert(sizeof(UUI_MultiplayerMenu_OLD_C) == 0x0004E8, "Wrong size on UUI_MultiplayerMenu_OLD_C");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, BackgroundDarken) == 0x000408, "Member 'UUI_MultiplayerMenu_OLD_C::BackgroundDarken' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow) == 0x000410, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_1) == 0x000418, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_1' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_2) == 0x000420, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_2' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_3) == 0x000428, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_3' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_4) == 0x000430, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_4' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_5) == 0x000438, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_5' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_6) == 0x000440, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_6' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_7) == 0x000448, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_7' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_8) == 0x000450, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_8' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_9) == 0x000458, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_9' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_10) == 0x000460, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_10' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_11) == 0x000468, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_11' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_12) == 0x000470, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_12' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_13) == 0x000478, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_13' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_14) == 0x000480, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_14' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_15) == 0x000488, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_15' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_16) == 0x000490, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_16' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_17) == 0x000498, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_17' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_18) == 0x0004A0, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_18' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_19) == 0x0004A8, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_19' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_20) == 0x0004B0, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_20' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_161) == 0x0004B8, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_161' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyFriendRow_293) == 0x0004C0, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyFriendRow_293' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyPlayerRow) == 0x0004C8, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyPlayerRow' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyPlayerRow_1) == 0x0004D0, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyPlayerRow_1' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyPlayerRow_118) == 0x0004D8, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyPlayerRow_118' has a wrong offset!");
static_assert(offsetof(UUI_MultiplayerMenu_OLD_C, UI_LobbyPlayerRow_252) == 0x0004E0, "Member 'UUI_MultiplayerMenu_OLD_C::UI_LobbyPlayerRow_252' has a wrong offset!");

}

