#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Ping_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Ping_OLD.UI_Ping_OLD_C
// 0x0000 (0x02C0 - 0x02C0)
class UUI_Ping_OLD_C final : public UCrabPingUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Ping_OLD_C">();
	}
	static class UUI_Ping_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Ping_OLD_C>();
	}
};
static_assert(alignof(UUI_Ping_OLD_C) == 0x000008, "Wrong alignment on UUI_Ping_OLD_C");
static_assert(sizeof(UUI_Ping_OLD_C) == 0x0002C0, "Wrong size on UUI_Ping_OLD_C");

}

