#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_PlayerName_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_PlayerName_OLD.UI_PlayerName_OLD_C
// 0x0008 (0x02C8 - 0x02C0)
class UUI_PlayerName_OLD_C final : public UCrabPlayerNameUI
{
public:
	class UImage*                                 TeamIcon;                                          // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_PlayerName_OLD_C">();
	}
	static class UUI_PlayerName_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_PlayerName_OLD_C>();
	}
};
static_assert(alignof(UUI_PlayerName_OLD_C) == 0x000008, "Wrong alignment on UUI_PlayerName_OLD_C");
static_assert(sizeof(UUI_PlayerName_OLD_C) == 0x0002C8, "Wrong size on UUI_PlayerName_OLD_C");
static_assert(offsetof(UUI_PlayerName_OLD_C, TeamIcon) == 0x0002C0, "Member 'UUI_PlayerName_OLD_C::TeamIcon' has a wrong offset!");

}

