#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_PlayerState

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_PlayerState.UI_PlayerState_C
// 0x0010 (0x0310 - 0x0300)
class UUI_PlayerState_C final : public UCrabPlayerStateUI
{
public:
	class UWidgetAnimation*                       OnUpdatedCrystalsAnim;                             // 0x0300(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Image_296;                                         // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_PlayerState_C">();
	}
	static class UUI_PlayerState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_PlayerState_C>();
	}
};
static_assert(alignof(UUI_PlayerState_C) == 0x000008, "Wrong alignment on UUI_PlayerState_C");
static_assert(sizeof(UUI_PlayerState_C) == 0x000310, "Wrong size on UUI_PlayerState_C");
static_assert(offsetof(UUI_PlayerState_C, OnUpdatedCrystalsAnim) == 0x000300, "Member 'UUI_PlayerState_C::OnUpdatedCrystalsAnim' has a wrong offset!");
static_assert(offsetof(UUI_PlayerState_C, Image_296) == 0x000308, "Member 'UUI_PlayerState_C::Image_296' has a wrong offset!");

}

