#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_SoundMenu

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_SoundMenu.UI_SoundMenu_C
// 0x0000 (0x02E0 - 0x02E0)
class UUI_SoundMenu_C final : public UCrabSoundMenuUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_SoundMenu_C">();
	}
	static class UUI_SoundMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_SoundMenu_C>();
	}
};
static_assert(alignof(UUI_SoundMenu_C) == 0x000008, "Wrong alignment on UUI_SoundMenu_C");
static_assert(sizeof(UUI_SoundMenu_C) == 0x0002E0, "Wrong size on UUI_SoundMenu_C");

}

