#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Slider

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Slider.UI_Slider_C
// 0x0000 (0x02D0 - 0x02D0)
class UUI_Slider_C final : public UCrabSliderUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Slider_C">();
	}
	static class UUI_Slider_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Slider_C>();
	}
};
static_assert(alignof(UUI_Slider_C) == 0x000008, "Wrong alignment on UUI_Slider_C");
static_assert(sizeof(UUI_Slider_C) == 0x0002D0, "Wrong size on UUI_Slider_C");

}

