#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Stats_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Stats_OLD.UI_Stats_OLD_C
// 0x0000 (0x03C0 - 0x03C0)
class UUI_Stats_OLD_C final : public UCrabStatsUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Stats_OLD_C">();
	}
	static class UUI_Stats_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Stats_OLD_C>();
	}
};
static_assert(alignof(UUI_Stats_OLD_C) == 0x000008, "Wrong alignment on UUI_Stats_OLD_C");
static_assert(sizeof(UUI_Stats_OLD_C) == 0x0003C0, "Wrong size on UUI_Stats_OLD_C");

}

