#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ShopPedestalUI_OLD

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_ShopPedestalUI_OLD.UI_ShopPedestalUI_OLD_C
// 0x0000 (0x02E8 - 0x02E8)
class UUI_ShopPedestalUI_OLD_C final : public UCrabShopPedestalUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_ShopPedestalUI_OLD_C">();
	}
	static class UUI_ShopPedestalUI_OLD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_ShopPedestalUI_OLD_C>();
	}
};
static_assert(alignof(UUI_ShopPedestalUI_OLD_C) == 0x000008, "Wrong alignment on UUI_ShopPedestalUI_OLD_C");
static_assert(sizeof(UUI_ShopPedestalUI_OLD_C) == 0x0002E8, "Wrong size on UUI_ShopPedestalUI_OLD_C");

}

