#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Sign

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Sign.UI_Sign_C
// 0x0008 (0x0268 - 0x0260)
class UUI_Sign_C final : public UUserWidget
{
public:
	class UTextBlock*                             SignText;                                          // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Sign_C">();
	}
	static class UUI_Sign_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Sign_C>();
	}
};
static_assert(alignof(UUI_Sign_C) == 0x000008, "Wrong alignment on UUI_Sign_C");
static_assert(sizeof(UUI_Sign_C) == 0x000268, "Wrong size on UUI_Sign_C");
static_assert(offsetof(UUI_Sign_C, SignText) == 0x000260, "Member 'UUI_Sign_C::SignText' has a wrong offset!");

}

