#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_SettingsMenu

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_SettingsMenu.UI_SettingsMenu_C
// 0x0018 (0x0418 - 0x0400)
class UUI_SettingsMenu_C final : public UCrabSettingsMenuUI
{
public:
	class UImage*                                 BackgroundDarken;                                  // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Divider;                                           // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Divider_1;                                         // 0x0410(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_SettingsMenu_C">();
	}
	static class UUI_SettingsMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_SettingsMenu_C>();
	}
};
static_assert(alignof(UUI_SettingsMenu_C) == 0x000008, "Wrong alignment on UUI_SettingsMenu_C");
static_assert(sizeof(UUI_SettingsMenu_C) == 0x000418, "Wrong size on UUI_SettingsMenu_C");
static_assert(offsetof(UUI_SettingsMenu_C, BackgroundDarken) == 0x000400, "Member 'UUI_SettingsMenu_C::BackgroundDarken' has a wrong offset!");
static_assert(offsetof(UUI_SettingsMenu_C, Divider) == 0x000408, "Member 'UUI_SettingsMenu_C::Divider' has a wrong offset!");
static_assert(offsetof(UUI_SettingsMenu_C, Divider_1) == 0x000410, "Member 'UUI_SettingsMenu_C::Divider_1' has a wrong offset!");

}

