#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_UnlockedCosmetic

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_UnlockedCosmetic.UI_UnlockedCosmetic_C
// 0x0000 (0x02E0 - 0x02E0)
class UUI_UnlockedCosmetic_C final : public UCrabUnlockedCosmeticUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_UnlockedCosmetic_C">();
	}
	static class UUI_UnlockedCosmetic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_UnlockedCosmetic_C>();
	}
};
static_assert(alignof(UUI_UnlockedCosmetic_C) == 0x000008, "Wrong alignment on UUI_UnlockedCosmetic_C");
static_assert(sizeof(UUI_UnlockedCosmetic_C) == 0x0002E0, "Wrong size on UUI_UnlockedCosmetic_C");

}

