#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_VideoMenu

#include "Basic.hpp"

#include "CrabChampions_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_VideoMenu.UI_VideoMenu_C
// 0x0000 (0x0460 - 0x0460)
class UUI_VideoMenu_C final : public UCrabVideoMenuUI
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_VideoMenu_C">();
	}
	static class UUI_VideoMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_VideoMenu_C>();
	}
};
static_assert(alignof(UUI_VideoMenu_C) == 0x000008, "Wrong alignment on UUI_VideoMenu_C");
static_assert(sizeof(UUI_VideoMenu_C) == 0x000460, "Wrong size on UUI_VideoMenu_C");

}

